# Generated by Django 2.1.15 on 2020-03-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadangInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('sex', models.BooleanField(default=False)),
                ('cardid', models.CharField(max_length=18)),
                ('tall', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('smoke', models.BooleanField(default=True)),
                ('drink', models.BooleanField(default=True)),
                ('ill', models.BooleanField(default=False)),
                ('HP_infection', models.BooleanField(default=False)),
                ('irregular_life', models.BooleanField(default=False)),
                ('environment_change', models.BooleanField(default=False)),
                ('Organ_change', models.BooleanField(default=False)),
            ],
        ),
    ]
